export const metadata = {
    title: 'Sam',
    description: 'Generated by Sam',
}

export default function marketingLayout({
    children,
} : {children: React.ReactNode}){
    return (
        <html lang="en">
            <body>
                <header className="bg-red text-center">
                    <h1> This is marketing Header </h1>
                </header>
                {children}
                <footer className="bg-gray-500 text-center">
                    <h1> This is marketing footer </h1>
                </footer>    
            </body>    
        </html>    
    )
}