export const metadata = {
    title: 'Sam',
    description: 'Generated by Sam',
}

export default function authLayout({
    children,
} : {children: React.ReactNode}){
    return (
        <html lang="en">
            <body>
                
                {children}
                <footer className="bg-gray-500 text-center">
                    <h1> This is Auth footer </h1>
                </footer>    
            </body>    
        </html>    
    )
}