import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata = {
  title: {
    default: "Default title",
    template: "%s | Sam ",
    absolute: "",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
};

// This is the root layout for the application, which includes a header and footer.
